name: wollok
version: 0.1.0.0
github: "githubuser/wollok"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# data-files:
# - wollok-ts/**/*.js
# - wollok-ts/**/package.json

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/wollok#readme>

dependencies:
- aeson
- aeson-pretty
- scientific
- bytestring
- text
- pretty-simple
- inline-js
- inline-js-core
- base >= 4.7 && < 5
- template-haskell
- interpolatedstring-perl6
- array

build-tools:
- happy
- alex
- BNFC

default-extensions:
- QuasiQuotes
- LambdaCase
- OverloadedStrings
- DeriveGeneric
- TypeApplications
- RecordWildCards
- DerivingStrategies
- DerivingVia

library:
  source-dirs: src

executables:
  wollok-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wollok

tests:
  wollok-test:
    main: WollokSpecMain
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - wollok
