-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

module Parser.AbsGrammar where

import Prelude (Char, Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

import qualified Data.Data    as C (Data, Typeable)
import qualified GHC.Generics as C (Generic)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic, Data.String.IsString)

data WFile = WFile [Import] [WLibraryElement] WProgram
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Import = Import
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WLibraryElement = WLibraryElement WClassDeclaration
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WProgram = WProgram Ident [WStatement]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WClassDeclaration
    = WClassDeclaration Ident WSuperclassDeclaration [WVariableDeclaration] [WMethodDeclaration]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WSuperclassDeclaration = WSuperclass Ident | WNoSuperclass
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WMethodDeclaration
    = WMethodDeclaration Ident [Ident] NativeIndicator MethodBody
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data NativeIndicator = Native | Custom
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data MethodBody = Implemented [WStatement] | NotImplemented
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WStatement
    = TopLevelExpression WExpression
    | VarDeclaration WVariableDeclaration
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WVariableDeclaration
    = WVariableDeclaration WVariableType Ident WExpression
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WVariableType = Var | Const
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data WExpression
    = WMessageSend WExpression Ident [WExpression]
    | WNumberLiteral Integer
    | WNullLiteral
    | WLiteralTrue
    | WLiteralFalse
    | WSelf
    | WStringLiteral String
    | WVariable Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

