{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Parser.
--   Generated by the BNF converter.

module Parser.PrintGrammar where

import qualified Parser.AbsGrammar
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Parser.AbsGrammar.Ident where
  prt _ (Parser.AbsGrammar.Ident i) = doc $ showString $ i
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Parser.AbsGrammar.WFile where
  prt i e = case e of
    Parser.AbsGrammar.WFile imports wlibraryelements wprogram -> prPrec i 0 (concatD [prt 0 imports, prt 0 wlibraryelements, prt 0 wprogram])

instance Print [Parser.AbsGrammar.Import] where
  prt = prtList

instance Print [Parser.AbsGrammar.WLibraryElement] where
  prt = prtList

instance Print Parser.AbsGrammar.Import where
  prt i e = case e of
    Parser.AbsGrammar.Import -> prPrec i 0 (concatD [doc (showString "import"), doc (showString "-"), doc (showString "TODO")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Parser.AbsGrammar.WLibraryElement where
  prt i e = case e of
    Parser.AbsGrammar.WLibraryElement wclassdeclaration -> prPrec i 0 (concatD [prt 0 wclassdeclaration])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Parser.AbsGrammar.WProgram where
  prt i e = case e of
    Parser.AbsGrammar.WProgram id wstatements -> prPrec i 0 (concatD [doc (showString "program"), prt 0 id, doc (showString "{"), prt 0 wstatements, doc (showString "}")])

instance Print [Parser.AbsGrammar.WStatement] where
  prt = prtList

instance Print Parser.AbsGrammar.WClassDeclaration where
  prt i e = case e of
    Parser.AbsGrammar.WClassDeclaration id wsuperclassdeclaration wvariabledeclarations wmethoddeclarations -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id, prt 0 wsuperclassdeclaration, doc (showString "{"), prt 0 wvariabledeclarations, prt 0 wmethoddeclarations, doc (showString "}")])

instance Print [Parser.AbsGrammar.WVariableDeclaration] where
  prt = prtList

instance Print [Parser.AbsGrammar.WMethodDeclaration] where
  prt = prtList

instance Print Parser.AbsGrammar.WSuperclassDeclaration where
  prt i e = case e of
    Parser.AbsGrammar.WSuperclass id -> prPrec i 0 (concatD [doc (showString "inherits"), prt 0 id])
    Parser.AbsGrammar.WNoSuperclass -> prPrec i 0 (concatD [])

instance Print Parser.AbsGrammar.WMethodDeclaration where
  prt i e = case e of
    Parser.AbsGrammar.WMethodDeclaration id ids nativeindicator methodbody -> prPrec i 0 (concatD [doc (showString "method"), prt 0 id, doc (showString "("), prt 0 ids, doc (showString ")"), prt 0 nativeindicator, prt 0 methodbody])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Parser.AbsGrammar.Ident] where
  prt = prtList

instance Print Parser.AbsGrammar.NativeIndicator where
  prt i e = case e of
    Parser.AbsGrammar.Native -> prPrec i 0 (concatD [doc (showString "native")])
    Parser.AbsGrammar.Custom -> prPrec i 0 (concatD [])

instance Print Parser.AbsGrammar.MethodBody where
  prt i e = case e of
    Parser.AbsGrammar.Implemented wstatements -> prPrec i 0 (concatD [doc (showString "{"), prt 0 wstatements, doc (showString "}")])
    Parser.AbsGrammar.NotImplemented -> prPrec i 0 (concatD [])

instance Print Parser.AbsGrammar.WStatement where
  prt i e = case e of
    Parser.AbsGrammar.TopLevelExpression wexpression -> prPrec i 0 (concatD [prt 0 wexpression])
    Parser.AbsGrammar.VarDeclaration wvariabledeclaration -> prPrec i 0 (concatD [prt 0 wvariabledeclaration])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Parser.AbsGrammar.WVariableDeclaration where
  prt i e = case e of
    Parser.AbsGrammar.WVariableDeclaration wvariabletype id wexpression -> prPrec i 0 (concatD [prt 0 wvariabletype, prt 0 id, doc (showString "="), prt 0 wexpression])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Parser.AbsGrammar.WVariableType where
  prt i e = case e of
    Parser.AbsGrammar.Var -> prPrec i 0 (concatD [doc (showString "var")])
    Parser.AbsGrammar.Const -> prPrec i 0 (concatD [doc (showString "const")])

instance Print Parser.AbsGrammar.WExpression where
  prt i e = case e of
    Parser.AbsGrammar.WMessageSend wexpression id wexpressions -> prPrec i 0 (concatD [prt 0 wexpression, doc (showString "."), prt 0 id, doc (showString "("), prt 0 wexpressions, doc (showString ")")])
    Parser.AbsGrammar.WNumberLiteral n -> prPrec i 1 (concatD [prt 0 n])
    Parser.AbsGrammar.WNullLiteral -> prPrec i 1 (concatD [doc (showString "null")])
    Parser.AbsGrammar.WLiteralTrue -> prPrec i 1 (concatD [doc (showString "true")])
    Parser.AbsGrammar.WLiteralFalse -> prPrec i 1 (concatD [doc (showString "false")])
    Parser.AbsGrammar.WSelf -> prPrec i 1 (concatD [doc (showString "self")])
    Parser.AbsGrammar.WStringLiteral str -> prPrec i 1 (concatD [prt 0 str])
    Parser.AbsGrammar.WVariable id -> prPrec i 1 (concatD [prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Parser.AbsGrammar.WExpression] where
  prt = prtList

